import './styles/globals.css'
import Footer from './components/footer/footer'
import NavBar from './components/navbar/navbar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />

      </body>
    </html>
  )
}
